# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  corepack = nodeEnv.buildNodePackage {
    name = "corepack";
    packageName = "corepack";
    version = "0.34.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/corepack/-/corepack-0.34.0.tgz";
      sha512 = "8D9N/k9hDjoISCDGUzH2wBF0fJD49p3G7ifoEZcc0vhB7Py6r+Mc1SpJ8dvnWY/HMP95K60WkQbN7vgbUgXgpA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      homepage = "https://github.com/nodejs/corepack#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
